### ISSUE TITLE
Opravné daňové doklady a doklady na přijatou zálohu

### ISSUE THREAD

**Issue by jkuchar** [kraag22/pohoda-export-faktur#1]
Jsou podporovány opravné daňové doklady a doklady na přijatou zálohu?

https://github.com/kraag22/pohoda-export-faktur/blob/master/invoice.php#L6

**Comment by kraag22** [comment]
Nevim, ale nerekl bych. Napsal sem jen minimum k tomu co sem potreboval

**Comment by jkuchar** [comment]
Diky
